#!/usr/bin/env bash
# ___________________________________________________________________________ #
#                                                                             #
#       Mvn-Sync -- Synchronize a Maven repository with a remote location.    #
#                                                                             #
#                                                                             #
#    Licensed under the Apache License, Version 2.0 (the "License");          #
#    you may not use this file except in compliance with the License.         #
#    You may obtain a copy of the License at                                  #
#                                                                             #
#        http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#    distributed under the License is distributed on an "AS IS" BASIS,        #
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
#    See the License for the specific language governing permissions and      #
#    limitations under the License.                                           #
# ___________________________________________________________________________ #
#                                                                             #
#                                                                             #
# Copyright 2010, lhunath                                                     #
#   * http://lhunath.lyndir.com                                               #
#   * Maarten Billemont.                                                      #
#                                                                             #
source mvn-tools || exit
cd "$root"

# Validate configuration.
[[ ! $syncTo || ! $syncToPath ]] && { emit -y "Remote host and/or remote repo for sync not set."; exit 1; }

update=1
[[ $1 = -U ]] && { update=; shift; }

# Sync.
find . \( -type d ! -execdir test -e pom.xml \; -prune \) -o \( -name src -o -name pom.xml \) -print0 | \
    rsync -avPr ${update:+-u} --delete-after -0 --files-from=- -e "ssh ${syncToPort:+-p $syncToPort}" "$@" . "$syncToHost:${syncToPath:-~}"
