#!/usr/bin/env bash
# ___________________________________________________________________________ #
#                                                                             #
#       Mvn-Auto -- Build and deploy outdated Maven artifacts.                #
#                                                                             #
#                                                                             #
#    Licensed under the Apache License, Version 2.0 (the "License");          #
#    you may not use this file except in compliance with the License.         #
#    You may obtain a copy of the License at                                  #
#                                                                             #
#        http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#    distributed under the License is distributed on an "AS IS" BASIS,        #
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
#    See the License for the specific language governing permissions and      #
#    limitations under the License.                                           #
# ___________________________________________________________________________ #
#                                                                             #
#                                                                             #
# Copyright 2010, lhunath                                                     #
#   * http://www.lhunath.com                                                  #
#   * Maarten Billemont.                                                      #
#                                                                             #
source mvn-tools || exit
# TODO: Support for deleted file detection:
#       When a file is deleted from a source tree, the artifact should be
#       added to the reactor and first cleaned.


# Functions.
# loadModules -- invoke whenever the modules array is needed.
loadModules() {
    (( ${#modules[@]} )) && return

    # Build list of all modules allowed in the maven reactor.
    IFS=$'\n' read -d '' -r -a profiles < <(xpathNodes ~/.m2/settings.xml '/settings/activeProfiles/activeProfile/text()') ||:
    emit "Enumerating modules in the Maven reactor" --
        modules=()
        addModules() {
            grep -qF '<module>' "$1" || return 0

            while read module; do

                moduleBase=${1%/pom.xml}
                modulePath=$moduleBase/$module
                modulePom=$modulePath/pom.xml
                [[ ! $module || ! -e $modulePom ]] && continue
                target=${modulePath#./}
                modules+=("$target")
                addModules "$modulePom"

            done < <(
                # Sub modules from the module's pom.xml's module list.
                xpathNodes "$1" '/project/modules/module/text()'

                # Profile-enabled sub modules from the module's pom.xml's profiles module lists.
                grep -qF '<profile>' "$1" && {
                    for profile in "${profiles[@]}"; do
                        xpathNodes "$1" "/project/profiles/profile/id[text()='$profile']/../modules/module/text()"
                    done
                }
            )
        }
        addModules ./pom.xml
    emit -$?
}


# Options.
while getopts :aABcCdDfnr:h arg; do
    case $arg in 
        a) autoFindArtifacts=1  ;;
        A) resetArtifacts=1     ;;
        B) nobuild=1            ;;
        c) clean=1              ;;
        C) cleanAll=1           ;;
        d) distribution=$OPTARG ;;
        D) nodistribution=1     ;;
        f) force=1              ;;
        n) nodeploy=1           ;;
        r) remote=$OPTARG       ;;

		h) showHelp \
			'Build and Deploy' \
			"Builds a set of artifacts and deploys the distribution on a remote host." \
			'lhunath' \
			\
			''                  "Each non-option argument is an additional artifact to include in the build." \
			''                  "See .mvntools.sample for creating a default configuration." \
            'Options'           '' \
            '-a'                "Automatically find outdated artifacts that need building." \
            '-A'                "Mark all targets under the current directory as up-to-date." \
			'-B'                "Don't Build.  Just upload and deploy the currently built distribution." \
			'-c'                "Clean the distribution before building it (eg. to rebuild its default/lib)." \
            '-C'                "Clean each artifact before building it (eg. when files were renamed/removed or to rebuild /lib)." \
			'-d distribution'   "The name in the reactor of the distribution artifact. (Default: [top dir name]-distribution)" \
            '-D'                "Do not try to build and deploy a distribution." \
            '-n'                "Do not try to deploy the distribution after building it."
			'-r user@host'      "Upload and deploy the distribution to user@host." \

			exit		;;
    esac
done
shift $((OPTIND-1))

# Validate parameters.
[[ $remote ]] || emit -y "Missing remote"
distribution=${distribution:-${PWD##*/}-distribution}
[[ -e $distribution ]] || distribution=
(( nodistribution )) && distribution=

if (( resetArtifacts )); then
    emit "Resetting all targets under the current directory" --
        find . -name pom.xml -exec bash -c 'shopt -s nullglob; touch . "${1%/pom.xml}/target/"*.{[jwe]ar,zip}' -- {} \;
    emit -$?
    exit
fi

while (( ! nobuild )); do

    if (( autoFindArtifacts )); then
        loadModules

        # Automatically find outdated artifacts.
        emit "Scanning for outdated artifacts"
        while read file; do
            files=("$file")
            [[ $file = ./pom.xml ]] && files=(*/pom.xml)

            for file in "${files[@]}"; do
                target=$file
                while [[ $target = */* && ! -e $target/pom.xml ]]
                do target=${target%/*}; done
                file=${file#$target}
                target=${target#./}

                # Only consider this target if it's in the module list.
                inArray "$target" "${modules[@]}" || continue

                emit "Adding (Outdated)  : $bold$target$reset:$file"
                targets+=("$PWD/$target")
            done
        done < <(find . \
                    \( -type d ! \( -exec bash -c 'test -e "$1/pom.xml"' -- {} \; -o -name 'src' -o -path '*/src/*' \) -prune \) -o \
                    -name 'pom.xml' -exec bash -c '
                        shopt -s nullglob
                        ref=( "${1%/pom.xml}"/target/*.{[jwe]ar,zip} )
                        if [[ -e $ref && $1 -nt $ref ]]; then
                            echo "$1"
                        fi
                        :' -- {} \; -o \
                    ! -type d -path '*/src/main/*' -exec bash -c '
                        shopt -s nullglob
                        for f; do
                            [[ ${f%%/src/main/*} != ${ref%/target/*} ]] && \
                                ref=( "${f%%/src/main/*}"/target/*[.]{[jwe]ar,zip} )
                            if [[ ! -e $ref ]]; then
                                continue
                                #while [[ $f = */* && ! -e $f/pom.xml ]]
                                #do f=${f%/*}; done
                                #echo "$f"
                            elif [[ $f -nt $ref ]]; then
                                echo "$f"
                            fi
                        done
                        :' -- {} + | sort -u)
    fi

    # Add manually specified targets.
    opts=()
    for target; do
        [[ $target = -* ]] && { opts+=("$target"); continue; }

        emit "Adding (Manual)    : $bold$target"
        targets+=("$PWD/$target")
    done
    cd "$root"

    (( ! ${#targets[@]} && ! force )) && {
        if ! ask -y!N 'No artifacts selected for build; build anyway?'; then
            if (( nodeploy || nodistribution )) || ! ask -Y!n 'Continue deployment with existing build?'; then
                exit
            fi

            break
        fi
    }

    # Add deploy artifacts.
    if (( ! nodistribution )); then
        loadModules

        while read pom; do
            if grep -q finalName "$pom" && grep -q $'<packaging>[ \t]*ear[ \t]*</' "$pom"; then
                target=${pom%/pom.xml}; target=${target#./}

                # Only consider this target if it's in the module list.
                inArray "$target" "${modules[@]}" || continue

                emit "Adding (FinalName) : $bold$target"
                targets+=("$target")
            fi
        done < <(find . -name 'pom.xml')
    fi

    targets=("${targets[@]#$PWD/}")

    # Begin the build.
    if (( ${#targets[@]} )); then
        echo
        emit "Building"
        mvn -pl "$(printf '%s,' "${targets[@]}")" -npu -amd "${opts[@]}" ${cleanAll:+clean} install & mvnpid=$!
        (( clean && ! nodistribution )) && [[ -e $distribution ]] && ( sleep 10; kill -0 $mvnpid 2>/dev/null && rm -rf "$distribution/target/" ) & cleanpid=$!
        trap "kill $mvnpid $cleanpid 2>/dev/null" EXIT
        wait $mvnpid
    fi

    break
done

if [[ -e $distribution ]] && (( ! nodeploy && ! nodistribution )); then

    # Upload the distribution.
    echo
    emit "Shutting down remote distribution"
    ssh -qt "$remote" "$(printf 's=%q/scripts/stop; [[ -e $s ]] || exit 0; "$s"' "${src%%/*}")"

    emit "Unpacking distribution"
    cd "$distribution/target/"
    unzip -uo "${distribution##*/}"-*.zip
    src=("${distribution##*/}"-*/*/); src=("${src[@]%/}")

    emit "Uploading distribution to $remote"
    ssh -qt "$remote" "$(printf 's=%q/scripts/stop; [[ -e $s ]] || exit 0; "$s" -w' "${src%%/*}")"
    rsync -avP --delete-delay "${src[@]}" "$remote":"${src%%/*}/"

    emit "(Re)Starting remote distribution"
    ssh -qt "$remote" "$(printf 'dist=%q
                                 "$dist/scripts/start" -f' "${src%%/*}")"
fi

# Print timestamp.
emit "Completed at $(date) after $SECONDS seconds."
